# Generated by Django 5.2.15 on 2026-06-26 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'db_table': 'empresas',
                'indexes': [models.Index(fields=['codigo'], name='empresas_codigo_814239_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParametroEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_costeo_codigo', models.CharField(default='PROMEDIO_PONDERADO', help_text='Código del método de costeo activo (catálogo MetodoCosteo en Fase 2).', max_length=30)),
                ('stock_negativo_permitido', models.BooleanField(default=False)),
                ('aprobacion_salida_requerida', models.BooleanField(default=True)),
                ('permite_cambio_metodo_costeo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='parametros', to='core.empresa')),
            ],
            options={
                'verbose_name': 'parámetro de empresa',
                'verbose_name_plural': 'parámetros de empresa',
                'db_table': 'parametrosempresa',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='core.empresa')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'db_table': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('es_transito', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bodegas', to='core.empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bodegas', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'bodega',
                'verbose_name_plural': 'bodegas',
                'db_table': 'bodegas',
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centroscosto', to='core.empresa')),
            ],
            options={
                'verbose_name': 'centro de costo',
                'verbose_name_plural': 'centros de costo',
                'db_table': 'centroscosto',
                'indexes': [models.Index(fields=['empresa', 'codigo'], name='centroscost_empresa_1eb3f5_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_cc_empresa_codigo')],
            },
        ),
        migrations.AddIndex(
            model_name='sucursal',
            index=models.Index(fields=['empresa', 'codigo'], name='sucursales_empresa_91d88c_idx'),
        ),
        migrations.AddConstraint(
            model_name='sucursal',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_sucursal_empresa_codigo'),
        ),
        migrations.AddIndex(
            model_name='bodega',
            index=models.Index(fields=['empresa', 'codigo'], name='bodegas_empresa_95277f_idx'),
        ),
        migrations.AddConstraint(
            model_name='bodega',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_bodega_empresa_codigo'),
        ),
    ]
