# Generated by Django 5.2.15 on 2026-06-26 16:03

import django.db.models.deletion
from django.db import migrations, models


def migrar_metodo_costeo(apps, schema_editor):
    ParametroEmpresa = apps.get_model('core', 'ParametroEmpresa')
    MetodoCosteo = apps.get_model('catalogs', 'MetodoCosteo')

    MetodoCosteo.objects.get_or_create(
        codigo='PROMEDIO_PONDERADO',
        defaults={
            'nombre': 'Promedio ponderado',
            'descripcion': 'Método de costeo por promedio ponderado.',
            'activo': True,
        },
    )
    MetodoCosteo.objects.get_or_create(
        codigo='FIFO',
        defaults={
            'nombre': 'FIFO',
            'descripcion': 'First In, First Out.',
            'activo': False,
        },
    )

    for parametro in ParametroEmpresa.objects.all():
        codigo = getattr(parametro, 'metodo_costeo_codigo', None) or 'PROMEDIO_PONDERADO'
        metodo = MetodoCosteo.objects.filter(codigo=codigo).first()
        if metodo is None:
            metodo = MetodoCosteo.objects.get(codigo='PROMEDIO_PONDERADO')
        parametro.metodo_costeo_id = metodo.pk
        parametro.save(update_fields=['metodo_costeo_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametroempresa',
            name='metodo_costeo',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='parametros_empresa',
                to='catalogs.metodocosteo',
            ),
        ),
        migrations.RunPython(migrar_metodo_costeo, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='parametroempresa',
            name='metodo_costeo_codigo',
        ),
    ]
