"""Permisos RBAC v1 — fuente idempotente (ver también fixtures/permisos_v1.json)."""

PERMISOS_V1 = [
    ('core.empresa.ver', 'Ver empresas', 'core', None, 'Consultar datos de empresas.'),
    ('core.empresa.editar', 'Editar empresas', 'core', None, 'Crear y modificar empresas.'),
    ('core.bodega.ver', 'Ver bodegas', 'core', None, 'Consultar bodegas y sucursales.'),
    ('core.bodega.editar', 'Editar bodegas', 'core', None, 'Crear y modificar bodegas y sucursales.'),
    ('core.parametro.editar', 'Editar parámetros de empresa', 'core', None, 'Modificar parámetros operativos.'),
    ('security.usuario.ver', 'Ver usuarios', 'security', None, 'Consultar usuarios del sistema.'),
    ('security.usuario.editar', 'Editar usuarios', 'security', None, 'Crear y modificar usuarios.'),
    ('security.rol.editar', 'Editar roles y permisos', 'security', None, 'Administrar roles y permisos.'),
    ('catalogs.ver', 'Ver catálogos', 'catalogs', None, 'Consultar catálogos maestros.'),
    ('catalogs.editar', 'Editar catálogos', 'catalogs', None, 'Crear y modificar catálogos maestros.'),
    ('inventory.producto.ver', 'Ver productos', 'inventory', None, 'Consultar productos.'),
    ('inventory.producto.editar', 'Editar productos', 'inventory', None, 'Crear y modificar productos.'),
    ('inventory.stock.ver', 'Ver stock y kardex', 'inventory', None, 'Consultar existencias y movimientos.'),
    ('inventory.movimiento.ver', 'Ver movimientos', 'inventory', None, 'Consultar movimientos de inventario.'),
    ('inventory.proveedor.editar', 'Editar proveedores', 'inventory', None, 'Crear y modificar proveedores.'),
    (
        'inventory.override_stock_negativo',
        'Forzar salida sin stock',
        'inventory',
        None,
        'Permitir salidas que dejen stock negativo con auditoría.',
    ),
    (
        'inventory.aprobar_ajuste',
        'Aprobar ajustes de inventario',
        'inventory',
        'AJUSTE',
        'Aprobar o rechazar ajustes de inventario físico.',
    ),
    (
        'operations.solicitud.crear',
        'Crear solicitudes',
        'operations',
        'SOLICITUD',
        'Crear solicitudes internas de salida.',
    ),
    (
        'operations.solicitud.aprobar',
        'Aprobar solicitudes',
        'operations',
        'SOLICITUD',
        'Aprobar o rechazar solicitudes.',
    ),
    (
        'operations.entrega.crear',
        'Crear y ejecutar entregas',
        'operations',
        'ENTREGA',
        'Crear y ejecutar entregas de material.',
    ),
    (
        'operations.entrega.aprobar',
        'Aprobar entregas ad-hoc',
        'operations',
        'ENTREGA',
        'Aprobar entregas sin solicitud previa.',
    ),
    (
        'operations.traslado.crear',
        'Crear traslados',
        'operations',
        'TRASLADO',
        'Crear traslados entre bodegas.',
    ),
    (
        'operations.traslado.aprobar',
        'Aprobar traslados',
        'operations',
        'TRASLADO',
        'Aprobar o rechazar traslados.',
    ),
    (
        'operations.traslado.despachar',
        'Despachar traslados',
        'operations',
        'TRASLADO',
        'Despachar traslados a estado en tránsito.',
    ),
    (
        'operations.traslado.recibir',
        'Recibir traslados',
        'operations',
        'TRASLADO',
        'Confirmar recepción de traslados en bodega destino.',
    ),
    (
        'operations.compra.crear',
        'Crear compras',
        'operations',
        'COMPRA',
        'Crear documentos de compra.',
    ),
    (
        'operations.compra.aprobar',
        'Aprobar compras',
        'operations',
        'COMPRA',
        'Aprobar o rechazar compras.',
    ),
    (
        'operations.compra.confirmar',
        'Confirmar recepción de compras',
        'operations',
        'COMPRA',
        'Confirmar recepción y generar entradas de inventario.',
    ),
    (
        'operations.documento.anular',
        'Anular documentos',
        'operations',
        None,
        'Anular documentos operativos según reglas de negocio.',
    ),
    ('support.adjunto.subir', 'Subir adjuntos', 'support', None, 'Adjuntar archivos a documentos.'),
    (
        'support.numerador.editar',
        'Editar numeradores',
        'support',
        None,
        'Configurar numeración de documentos por empresa.',
    ),
]
