# Generated by Django 5.2.15 on 2026-06-26 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_parametroempresa_metodo_costeo_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Custodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('documento_identidad', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodios', to='core.empresa')),
            ],
            options={
                'verbose_name': 'custodio',
                'verbose_name_plural': 'custodios',
                'db_table': 'custodios',
            },
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=50)),
                ('documento_id', models.CharField(max_length=50)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='core.empresa')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'adjunto',
                'verbose_name_plural': 'adjuntos',
                'db_table': 'adjuntos',
                'indexes': [models.Index(fields=['empresa', 'modulo', 'documento_id'], name='adjuntos_empresa_abcab1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Numerador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=40)),
                ('prefijo', models.CharField(blank=True, max_length=20, null=True)),
                ('ultimo_numero', models.BigIntegerField(default=0)),
                ('longitud', models.IntegerField(blank=True, default=6, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numeradores', to='core.empresa')),
            ],
            options={
                'verbose_name': 'numerador',
                'verbose_name_plural': 'numeradores',
                'db_table': 'numeradores',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'tipo_documento'), name='uq_numerador_empresa_tipo')],
            },
        ),
        migrations.CreateModel(
            name='UbicacionBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(blank=True, max_length=40, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='core.bodega')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_bodega', to='core.empresa')),
                ('ubicacion_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_hijas', to='support.ubicacionbodega')),
            ],
            options={
                'verbose_name': 'ubicación de bodega',
                'verbose_name_plural': 'ubicaciones de bodega',
                'db_table': 'ubicaciones_bodega',
                'constraints': [models.UniqueConstraint(fields=('bodega', 'codigo'), name='uq_ubicacion_bodega_codigo')],
            },
        ),
    ]
