# Generated by Django 5.2.15 on 2026-06-26 16:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('core', '0002_remove_parametroempresa_metodo_costeo_codigo_and_more'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=120)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='core.empresa')),
            ],
            options={
                'verbose_name': 'lote',
                'verbose_name_plural': 'lotes',
                'db_table': 'lotes',
            },
        ),
        migrations.CreateModel(
            name='CapaCosteoFifo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField()),
                ('cantidad_inicial', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cantidad_consumida', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('cantidad_saldo', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cerrada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capas_costeo_fifo', to='core.bodega')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capas_costeo_fifo', to='core.empresa')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capas_costeo_fifo', to='inventory.lote')),
            ],
            options={
                'verbose_name': 'capa de costeo FIFO',
                'verbose_name_plural': 'capas de costeo FIFO',
                'db_table': 'capas_costeo_fifo',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('costo_total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('referencia_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_id', models.CharField(blank=True, max_length=50, null=True)),
                ('anulado', models.BooleanField(default=False)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bodega_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='core.bodega')),
                ('bodega_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='core.bodega')),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='core.centrocosto')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='core.empresa')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventory.lote')),
                ('metodo_costeo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalogs.metodocosteo')),
                ('movimiento_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversas', to='inventory.movimientoinventario')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalogs.tipomovimientoinventario')),
                ('ubicacion_bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='support.ubicacionbodega')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'db_table': 'movimientosinventario',
            },
        ),
        migrations.CreateModel(
            name='ConsumoCapaFifo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capa_fifo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='inventory.capacosteofifo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_capa_fifo', to='core.empresa')),
                ('movimiento_salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_capa_fifo', to='inventory.movimientoinventario')),
            ],
            options={
                'verbose_name': 'consumo de capa FIFO',
                'verbose_name_plural': 'consumos de capa FIFO',
                'db_table': 'consumo_capas_fifo',
            },
        ),
        migrations.AddField(
            model_name='capacosteofifo',
            name='movimiento_entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capas_fifo_generadas', to='inventory.movimientoinventario'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('maneja_stock', models.BooleanField(default=True)),
                ('permite_stock_negativo', models.BooleanField(default=False)),
                ('requiere_aprobacion_salida', models.BooleanField(default=False)),
                ('costo_promedio_actual', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('factor_conversion', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogs.categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.empresa')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogs.marca')),
                ('tipo_control_inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogs.tipocontrolinventario')),
                ('unidad_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_compra', to='catalogs.unidadmedida')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_base', to='catalogs.unidadmedida')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'productos',
            },
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventory.producto'),
        ),
        migrations.AddField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventory.producto'),
        ),
        migrations.AddField(
            model_name='capacosteofifo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capas_costeo_fifo', to='inventory.producto'),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('razon_social', models.CharField(max_length=180)),
                ('nombre_contacto', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='core.empresa')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=120)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('bodega_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series', to='core.bodega')),
                ('centro_costo_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series', to='core.centrocosto')),
                ('custodio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series', to='support.custodio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='core.empresa')),
                ('estado_serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='catalogs.estadoserie')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='inventory.producto')),
                ('ubicacion_bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series', to='support.ubicacionbodega')),
            ],
            options={
                'verbose_name': 'serie',
                'verbose_name_plural': 'series',
                'db_table': 'series',
            },
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventory.serie'),
        ),
        migrations.CreateModel(
            name='StockActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('costo_promedio', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_actuales', to='core.bodega')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_actuales', to='core.empresa')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks_actuales', to='inventory.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_actuales', to='inventory.producto')),
            ],
            options={
                'verbose_name': 'stock actual',
                'verbose_name_plural': 'stocks actuales',
                'db_table': 'stockactual',
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'sku'], name='productos_empresa_f0e342_idx'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('empresa', 'sku'), name='uq_producto_empresa_sku'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('empresa', 'producto', 'codigo_lote'), name='uq_lote_producto_codigo'),
        ),
        migrations.AddIndex(
            model_name='capacosteofifo',
            index=models.Index(fields=['empresa', 'producto', 'bodega', 'fecha_entrada'], name='capas_coste_empresa_467a25_idx'),
        ),
        migrations.AddConstraint(
            model_name='serie',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_serie'), name='uq_serie_empresa_numero'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['empresa', 'producto', 'created_at'], name='movimientos_empresa_5f69b5_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['empresa', 'referencia_tipo', 'referencia_id'], name='movimientos_empresa_76833d_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockactual',
            constraint=models.UniqueConstraint(condition=models.Q(('lote__isnull', False)), fields=('empresa', 'bodega', 'producto', 'lote'), name='uq_stock_con_lote'),
        ),
        migrations.AddConstraint(
            model_name='stockactual',
            constraint=models.UniqueConstraint(condition=models.Q(('lote__isnull', True)), fields=('empresa', 'bodega', 'producto'), name='uq_stock_sin_lote'),
        ),
    ]
