/** Textos UI para pantallas de documento. */
export const DOCUMENT_UI = {
  recepcion: {
    loading: 'Cargando recepción…',
    errorTitle: 'Recepción no disponible',
    errorDescription: 'No se pudo cargar el documento. Intente de nuevo.',
    emptyTitle: 'Recepción no encontrada',
    emptyDescription: 'No hay compras abiertas para recepcionar. Cree una en operaciones o use ?id= en la URL.',
    linesCaption: 'Líneas de recepción',
    addLine: 'Agregar línea',
    saveDraft: 'Guardar borrador',
    confirm: 'Confirmar recepción',
    cancel: 'Cancelar',
    void: 'Anular',
    saving: 'Guardando…',
    confirming: 'Confirmando…',
    headerZone: 'HDR',
    headerTitle: 'Cabecera del documento',
    linesZone: 'LIN',
    linesTitle: 'Líneas de recepción',
    summaryZone: 'SUM',
    summaryTitle: 'Resumen',
    fields: {
      supplier: 'Proveedor',
      purchaseOrder: 'Nº orden compra',
      date: 'Fecha recepción',
      warehouse: 'Bodega destino',
      notes: 'Observaciones',
      notesPlaceholder: 'Notas del operador, referencia de guía…',
    },
    strip: {
      date: 'Fecha',
      supplier: 'Proveedor',
      warehouse: 'Bodega',
      purchaseOrder: 'Orden compra',
    },
    summary: {
      lines: 'Líneas',
      units: 'Total unidades',
      differences: 'Con diferencia',
      operator: 'Operador',
    },
    columns: {
      line: '#',
      sku: 'SKU',
      description: 'Descripción',
      expected: 'Cant. esperada',
      received: 'Cant. recibida',
      status: 'Estado línea',
      location: 'Ubicación',
      batch: 'Lote',
    },
  },
  despacho: {
    loading: 'Cargando despacho…',
    errorTitle: 'Despacho no disponible',
    errorDescription: 'No se pudo cargar el documento. Intente de nuevo.',
    emptyTitle: 'Despacho no encontrado',
    emptyDescription:
      'No hay entregas abiertas para despachar. Cree una en operaciones o use ?id= en la URL.',
    linesCaption: 'Líneas de despacho',
    addLine: 'Agregar línea',
    saveDraft: 'Guardar borrador',
    confirm: 'Confirmar despacho',
    cancel: 'Cancelar',
    void: 'Anular',
    saving: 'Guardando…',
    confirming: 'Confirmando…',
    headerZone: 'HDR',
    headerTitle: 'Cabecera del documento',
    linesZone: 'LIN',
    linesTitle: 'Líneas de despacho',
    fields: {
      client: 'Cliente / destino',
      orderRef: 'Nº pedido',
      date: 'Fecha despacho',
      warehouse: 'Bodega origen',
      carrier: 'Transportista',
      notes: 'Observaciones',
      notesPlaceholder: 'Instrucciones de entrega, contacto en obra…',
    },
    strip: {
      client: 'Cliente / destino',
      warehouse: 'Bodega salida',
      orderRef: 'Pedido / solicitud',
      date: 'Fecha',
    },
    summary: {
      lines: 'Líneas',
      committed: 'Unidades comprometidas',
      dispatched: 'Unidades despachadas',
      differences: 'Con diferencia',
      operator: 'Operador',
    },
    columns: {
      line: '#',
      sku: 'SKU',
      description: 'Descripción',
      committed: 'Cant. comprometida',
      dispatch: 'Cant. a despachar',
      status: 'Estado línea',
      location: 'Ubicación',
    },
  },
  traslado: {
    loading: 'Cargando traslado…',
    errorTitle: 'Traslado no disponible',
    errorDescription: 'No se pudo cargar el documento. Intente de nuevo.',
    emptyTitle: 'Traslado no encontrado',
    emptyDescription:
      'No hay traslados abiertos para mostrar. Cree uno en operaciones o use ?id= en la URL.',
    linesCaption: 'Líneas de traslado',
    addLine: 'Agregar línea',
    saveDraft: 'Guardar borrador',
    confirm: 'Confirmar traslado',
    cancel: 'Cancelar',
    void: 'Anular',
    saving: 'Guardando…',
    confirming: 'Confirmando…',
    headerZone: 'HDR',
    headerTitle: 'Cabecera del documento',
    linesZone: 'LIN',
    linesTitle: 'Líneas de traslado',
    fields: {
      warehouseOrigin: 'Bodega origen',
      warehouseDest: 'Bodega destino',
      reason: 'Motivo de traslado',
      date: 'Fecha',
      notes: 'Observaciones',
      notesPlaceholder: 'Detalle del movimiento interno, autorización…',
    },
    strip: {
      warehouseOrigin: 'Bodega origen',
      warehouseDest: 'Bodega destino',
      reason: 'Motivo',
      date: 'Fecha',
    },
    summary: {
      lines: 'Líneas',
      planned: 'Unidades planificadas',
      transferred: 'Unidades trasladadas',
      differences: 'Con diferencia',
      operator: 'Operador',
    },
    columns: {
      line: '#',
      sku: 'SKU',
      description: 'Descripción',
      transfer: 'Cant. a trasladar',
      origin: 'Ubicación origen',
      dest: 'Ubicación destino',
      status: 'Estado línea',
    },
  },
  ajuste: {
    loading: 'Cargando ajuste…',
    errorTitle: 'Ajuste no disponible',
    errorDescription: 'No se pudo cargar el documento. Intente de nuevo.',
    linesCaption: 'Líneas de ajuste',
    addLine: 'Agregar línea',
    saveDraft: 'Guardar borrador',
    confirm: 'Confirmar ajuste',
    cancel: 'Cancelar',
    void: 'Anular',
    saving: 'Guardando…',
    confirming: 'Confirmando…',
    headerZone: 'HDR',
    headerTitle: 'Cabecera del documento',
    linesZone: 'LIN',
    linesTitle: 'Líneas de ajuste',
    approvalAlertTitle: 'Ajuste requiere aprobación',
    approvalAlertMessage:
      'Los ajustes negativos superiores a 5 unidades requieren autorización de supervisor.',
    fields: {
      warehouse: 'Bodega',
      adjustType: 'Tipo de ajuste',
      reason: 'Motivo',
      date: 'Fecha',
      notes: 'Observaciones',
      notesPlaceholder: 'Justificación del ajuste, referencia de conteo…',
    },
    strip: {
      adjustType: 'Tipo de ajuste',
      warehouse: 'Bodega',
      date: 'Fecha',
      countRef: 'Ref. conteo',
    },
    summary: {
      lines: 'Líneas',
      adjusted: 'Unidades ajustadas',
      totalDifference: 'Diferencia total',
      differences: 'Líneas con diferencia',
      operator: 'Operador',
    },
    columns: {
      line: '#',
      sku: 'SKU',
      description: 'Descripción',
      theoretical: 'Stock teórico',
      physical: 'Stock físico',
      difference: 'Diferencia',
      differenceType: 'Tipo diferencia',
      location: 'Ubicación',
      status: 'Estado línea',
    },
  },
} as const
