# Generated by Django 5.2.15 on 2026-06-26 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('core', '0002_remove_parametroempresa_metodo_costeo_codigo_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60)),
                ('fecha_ajuste', models.DateField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_aprobados', to=settings.AUTH_USER_MODEL)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bodega')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.estadodocumento')),
            ],
            options={
                'verbose_name': 'ajuste de inventario',
                'verbose_name_plural': 'ajustes de inventario',
                'db_table': 'ajustesinventario',
            },
        ),
        migrations.CreateModel(
            name='AjusteInventarioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sistema', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('cantidad_contada', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('ajuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='operations.ajusteinventario')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.producto')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.serie')),
            ],
            options={
                'verbose_name': 'detalle de ajuste',
                'verbose_name_plural': 'detalles de ajuste',
                'db_table': 'ajustesinventariodetalle',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60)),
                ('fecha_compra', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bodega')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.estadodocumento')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.proveedor')),
            ],
            options={
                'verbose_name': 'compra',
                'verbose_name_plural': 'compras',
                'db_table': 'compras',
            },
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, max_length=120, null=True)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='operations.compra')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.producto')),
            ],
            options={
                'verbose_name': 'detalle de compra',
                'verbose_name_plural': 'detalles de compra',
                'db_table': 'comprasdetalle',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60)),
                ('fecha_entrega', models.DateField()),
                ('recibido_por', models.CharField(blank=True, max_length=150, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('es_ad_hoc', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bodega')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.centrocosto')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.estadodocumento')),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'entregas',
                'db_table': 'entregas',
            },
        ),
        migrations.CreateModel(
            name='EntregaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entregada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='operations.entrega')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.producto')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.serie')),
            ],
            options={
                'verbose_name': 'detalle de entrega',
                'verbose_name_plural': 'detalles de entrega',
                'db_table': 'entregasdetalle',
            },
        ),
        migrations.CreateModel(
            name='EstadoHistorialDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_tipo', models.CharField(max_length=40)),
                ('documento_id', models.CharField(max_length=50)),
                ('estado_anterior', models.CharField(blank=True, max_length=40, null=True)),
                ('estado_nuevo', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial de estado de documento',
                'verbose_name_plural': 'historial de estados de documento',
                'db_table': 'estadohistorialdocumento',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60)),
                ('fecha_solicitud', models.DateField()),
                ('prioridad', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.centrocosto')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.estadodocumento')),
            ],
            options={
                'verbose_name': 'solicitud',
                'verbose_name_plural': 'solicitudes',
                'db_table': 'solicitudes',
            },
        ),
        migrations.AddField(
            model_name='entrega',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='operations.solicitud'),
        ),
        migrations.CreateModel(
            name='SolicitudDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cantidad_aprobada', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.producto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='operations.solicitud')),
            ],
            options={
                'verbose_name': 'detalle de solicitud',
                'verbose_name_plural': 'detalles de solicitud',
                'db_table': 'solicitudesdetalle',
            },
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_aprobados', to=settings.AUTH_USER_MODEL)),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_destino', to='core.bodega')),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_origen', to='core.bodega')),
                ('bodega_transito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_transito', to='core.bodega')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.estadodocumento')),
            ],
            options={
                'verbose_name': 'traslado',
                'verbose_name_plural': 'traslados',
                'db_table': 'traslados',
            },
        ),
        migrations.CreateModel(
            name='TrasladoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_trasladada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.producto')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.serie')),
                ('traslado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='operations.traslado')),
            ],
            options={
                'verbose_name': 'detalle de traslado',
                'verbose_name_plural': 'detalles de traslado',
                'db_table': 'trasladosdetalle',
            },
        ),
        migrations.AddConstraint(
            model_name='ajusteinventario',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uq_ajuste_empresa_numero'),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uq_compra_empresa_numero'),
        ),
        migrations.AddIndex(
            model_name='estadohistorialdocumento',
            index=models.Index(fields=['empresa', 'documento_tipo', 'documento_id'], name='estadohisto_empresa_0f96a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='solicitud',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uq_solicitud_empresa_numero'),
        ),
        migrations.AddConstraint(
            model_name='entrega',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uq_entrega_empresa_numero'),
        ),
        migrations.AddConstraint(
            model_name='traslado',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uq_traslado_empresa_numero'),
        ),
    ]
