# Generated by Django 5.2.15 on 2026-06-28 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
        ('core', '0002_remove_parametroempresa_metodo_costeo_codigo_and_more'),
        ('inventory', '0001_initial'),
        ('operations', '0002_solicituddetalle_serie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ajusteinventario',
            index=models.Index(fields=['empresa', 'created_at'], name='ajustesinve_empresa_de1f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='ajusteinventario',
            index=models.Index(fields=['empresa', 'estado'], name='ajustesinve_empresa_36edab_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['empresa', 'created_at'], name='compras_empresa_ef898f_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['empresa', 'estado'], name='compras_empresa_040126_idx'),
        ),
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['empresa', 'created_at'], name='entregas_empresa_948ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['empresa', 'estado'], name='entregas_empresa_99419a_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['empresa', 'created_at'], name='solicitudes_empresa_032f40_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['empresa', 'estado'], name='solicitudes_empresa_c47dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='traslado',
            index=models.Index(fields=['empresa', 'created_at'], name='traslados_empresa_c59cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='traslado',
            index=models.Index(fields=['empresa', 'estado'], name='traslados_empresa_ff2eb8_idx'),
        ),
    ]
